<?php

define('DS', '/');
define('ZCMS_CACHE_CORE_SYSTEM','ZCMS_CACHE_CORE_SYSTEM');
define('ZCMS_CACHE_MODEL','ZCMS_CACHE_MODEL');
define('ZCMS_CACHE_MODULES', 'ZCMS_CACHE_MODULES');
define('ZCMS_VERSION', '2.0.1');
define('PHP_VERSION_REQUIRED', '5.5.x');
define('PHALCON_VERSION_REQUIRED', '2.0.2');
define('MAX_AVATAR_SIZE_UPLOAD', 2097152); //MAX 2MB
define('MAX_IMAGE_SIZE_UPLOAD', 2097152); //MAX 2MB
define('USER_AVATAR_FOLDER_UPLOAD', '/media/users');
define('USER_AVATAR_DEFAULT', '/media/users/default.png');
define('ROOT_USER_AVATAR_FOLDER_UPLOAD', ROOT_PATH . '/public' . USER_AVATAR_FOLDER_UPLOAD);

